version: '2'

services:
#  redis:
#    image: 'redis:3.0-alpine'
#    command: redis-server --requirepass devpassword
#    volumes:
#      - 'redis:/data'
#    ports:
#      - '6379:6379'

  db:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    env_file: .env

  server:
    build: ./server
    volumes:
      - './server/src:/app/src'
      - './server/pickles:/app/pickles'
      - './server/static:/app/static'
      - './server/util:/app/util'
    ports:
      - '80:80'
    depends_on:
      - db

#  celery:
#    build: .
#    command: celery worker -l info -A snakeeyes.blueprints.contact.tasks
#    volumes:
#      - '.:/snakeeyes'

volumes:
  redis:
